### ISSUE TITLE
두 항목을 가지는 이벤트 관련 버그

### ISSUE THREAD

**Issue by thxthanks** [patrick-choe/EditorHelper#16]
https://user-images.githubusercontent.com/94922363/143067454-ac558eb0-97db-449f-9c51-bdb90b8a8ffa.mp4
두 항목이 존재하는 이벤트중 한 항목을 공백으로 비울시 두 항목 모두 0이 됩니다. 공백으로 비운 항목만 0으로 설정하면 좋을 듯 합니다

**Comment by papertoy1127** [comment]
공식 지원
