### ISSUE TITLE
[Bug] 이벤트번들 페이지 선택 안됨

### ISSUE THREAD

**Issue by tjwogud** [patrick-choe/EditorHelper#17]
게임 버젼: 알파(r78)
에디터헬퍼 버젼: 2.0 beta3
다른 모드: 없음

에디터에서 이벤트번들 탭을 클릭할 시, 화면은 뜨지만 탭이 선택이 안된 채로 있습니다.
![image](https://user-images.githubusercontent.com/70669642/143682396-cccd433d-6990-40ed-922c-7e2c9aaf778d.png)

**Comment by papertoy1127** [comment]
아마 해결된 문제같습니다
