### ISSUE TITLE
이 모드는 무엇으로 빌드해야하나요?

### ISSUE THREAD

**Issue by xenon245** [patrick-choe/EditorHelper#3]
build.bat을 어떤 프로그램으로 실행시켜야 빌드할 수 있나요?

**Comment by patrick-choe** [comment]
build.bat 파일을 **리눅스 명령어 사용이 가능한 윈도우 환경** 에서 실행하시면 됩니다.
저는 윈도우 git에 내장되어있는 것을 사용하였습니다 (git 경로/usr/bin)

**Comment by patrick-choe** [comment]
수정) MSBuild의 경로 또한 환경에 맞게 변경이 필요합니다.

**Comment by xenon245** [comment]
Git에서 어떤 명령어를 사용해야 하나요?

**Comment by patrick-choe** [comment]
> Git에서 어떤 명령어로 빌드 해요? 제가 git을 잘 몰라가지고 ㅜㅜ

git의 명령어로 빌드하는것이 아닌, 윈도우 git에 포함되어 있는 것을 이용하여 실행시키는 겁니다.

PATH에 git 경로/usr/bin (저의 경우에는 C:\Program Files\Git\usr\bin) 을 추가 후, build.bat MSBuild의 경로 수정을 하고 (dotnet sdk 버전에 따라 다를겁니다) build.bat을 실행하시면 됩니다.

안정적인 빌드는 모딩 커뮤니티에 올라와 있으니 (1.3.0-r75) 받아서 사용하시면 됩니다.
모딩 커뮤니티: discord (dot) gg / YfVKH4WtvP
